import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import { Alert, Box, Button, Grid, Typography } from "@mui/material";
import DisplayTimeline from "~/components/Timeline";
import Upload from "~/components/Upload";
import DisplayImages from "~/components/DisplayImages";
import ImageActions from "~/components/ImageActions";
import DisplayEvents from "~/components/DisplayEvents";
import { useState } from "react";

const Home: NextPage = () => {
  const [directoryName, setDirectoryName] = useState<string>("");
  const [selectedImages, setSelectedImages] = useState<Array<string>>([]);

  return (
    <>
      <Head>
        <title>Delta Scope</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Grid
          container
          spacing={2}
          xs={12}
          direction={"row"}
          justifyContent="center"
          alignItems="center"
          height={"100vh"}
        >
          <Grid item xs={12}>
            <Typography
              variant="h3"
              sx={{ fontWeight: "1.5rem", color: "black", marginTop: "1rem" }}
            >
              Delta Scope
            </Typography>
          </Grid>

          <Grid
            container
            spacing={2}
            xs={12}
            direction={"row"}
            justifyContent="center"
            alignItems="center"
          >
            {/* Timeline */}
            {/* <Grid container xs={12} justifyContent="center">
              <Timeline />
            </Grid> */}

            <Grid container spacing={2} xs={12}>
              {/* Get images & initiate delta */}
              <Grid
                container
                spacing={2}
                xs={4}
                direction={"row"}
                justifyContent="center"
                alignItems="center"
                sx={{ border: "1px solid red", padding: "1rem" }}
                zeroMinWidth
              >
                <Typography
                  variant="h2"
                  sx={{
                    fontSize: "2.25rem",
                    fontWeight: "bolder",
                    textAlign: "center",
                  }}
                >
                  Images
                </Typography>
                <Upload />
                <DisplayImages
                  setParentDirectoryName={setDirectoryName}
                  setImages={setSelectedImages}
                />
              </Grid>

              {/* Menu & File Differences + Events */}
              <Grid item xs={8}>
                <ImageActions directory={directoryName} images={selectedImages} />
              </Grid>
            </Grid>
          </Grid>
        </Grid>
      </main>
    </>
  );
};

export default Home;
