import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import { Alert, Box, Button, Grid, Typography } from "@mui/material";
import Timeline from "~/components/Timeline";
import Upload from "~/components/Upload";
import FileDisplay from "~/components/DisplayFile";
import DisplayImages from "~/components/DisplayImages";
import ImageActions from "~/components/OptionsMenu";
import DisplayEvents from "~/components/DisplayEvents";
import { useState } from "react";

const Home: NextPage = () => {
  const [directoryName, setDirectoryName] = useState<string>("");

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box sx={{ backgroundColor: '#191919' ,display: 'flex', flexDirection: 'column', justifyContent: 'center', alignItems: 'center', minHeight: '100vh', minWidth: '100vw' }} >
          <Box sx={{ fontSize: '1.5rem', width: '100vw', position: 'absolute', top: 0, textAlign: 'center' }} >
            <Typography  variant="h3" sx={{ fontWeight: '1.5rem', color: 'white', marginTop: '1rem'}} >Delta Scope</Typography>
          </Box>
          <Box sx={{ display: 'flex', flexDirection: 'column', justifyContent: 'space-between', columnGap: '1rem' }} >
            {/* Timeline */}
            <Box sx={{ display: 'flex', flexDirection: 'row' ,justifyContent: 'center', alignItems: 'center' }}>
              <Timeline />
            </Box>
            <Box sx={{ display: 'flex', flexDirection: 'row', justifyContent: 'space-between' }} >
              {/* File */}
              <Box sx={{}}>
                <Upload />
                <DisplayImages directoryName={directoryName} />
                {/* TODO: Add display files images */}
              </Box>
              {/* Menu & File Differences + Events */}
              <Box>
                <ImageActions />
              </Box>
            </Box>
          </Box>
        </Box>
      </main>
    </>
  );
};

export default Home;
