import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import { Alert, Box, Button, Grid, Typography } from "@mui/material";
import DisplayTimeline from "~/components/Timeline";
import Upload from "~/components/Upload";
import DisplayImages from "~/components/DisplayImages";
import ImageActions from "~/components/ImageActions";
import DisplayEvents from "~/components/DisplayEvents";
import { useState } from "react";

const Home: NextPage = () => {
  const [directoryName, setDirectoryName] = useState<string>("");
  const [selectedImages, setSelectedImages] = useState<Array<string>>([]);

  return (
    <>
      <Head>
        <title>Delta Scope</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Grid container spacing="2">
          <Grid
            item
            container
            sx={{ textAlign: "center" }}
            justifyContent="center"
          >
            <h1>Deltascope</h1>
          </Grid>
          <Grid
            item
            container
            // sx={{ textAlign: "center" }}
            // justifyContent="center"
          >
            <DisplayTimeline />
          </Grid>

          <Grid item container spacing={2}>
            {/* Images */}
            <DisplayImages setParentDirectoryName={setDirectoryName}
            setImages={setSelectedImages} 
            />

            {/* Events */}
            <ImageActions directory={directoryName} images={selectedImages} />
          </Grid>

        </Grid>
      </main>
    </>
  );
};

export default Home;
